project:
  type: book

book:
  title: "Fantasy Premier League"
  author: "Janarth Duraisingham"
  #date: "07/09/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



